////// First Exercise

let Names =[

    [ "Alghalia" ,"Aljoharah", "Abdullah", "Abdulaziz"] 

 ]
 console.log(Names);
 console.log(Names [2,2]);


 
 /// push & Unshift 

let NAmes = ["Alghalia" ,"Aljoharah", "Abdullah", "Abdulaziz"]
NAmes . unshift("Asayel") ;
console.log(NAmes);
NAmes. push("Nawaf");
console.log(NAmes);



// Slice 

let NAMes = ["Alghalia" ,"Aljoharah", "Abdullah", "Abdulaziz"]
console.log(NAMes.slice(-3));
console.log(NAMes . slice (0,-1));


